# Generated by Django 2.2 on 2020-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritearticle',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='articletag',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='标签标题图'),
        ),
    ]
