# Generated by Django 2.2 on 2020-08-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_text',
            field=models.TextField(verbose_name='文章文本内容'),
        ),
    ]
