# Generated by Django 2.2 on 2020-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200816_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(1, '普通用户'), (2, '管理员'), (3, '博主')], default=1, null=True, verbose_name='角色'),
        ),
    ]
