# Generated by Django 2.2 on 2020-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200825_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=64, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
