# Generated by Django 2.2 on 2020-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200825_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.CharField(max_length=128, verbose_name='男孩姓名')),
                ('girl', models.CharField(max_length=128, verbose_name='女孩姓名')),
                ('boyavatar', models.CharField(blank=True, max_length=256, null=True, verbose_name='男孩头像')),
                ('girlavatar', models.CharField(blank=True, max_length=256, null=True, verbose_name='女孩头像')),
                ('togetherdate', models.DateTimeField(verbose_name='在一起时间')),
            ],
        ),
    ]
