# Generated by Django 2.2 on 2020-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lovers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovers',
            name='togetherdate',
            field=models.CharField(max_length=256, verbose_name='在一起时间'),
        ),
    ]
