# Generated by Django 2.2 on 2020-10-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201008_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
    ]
